In [3]:
#import
import numpy as np
import pandas as pd
import scipy
from math import sqrt
import matplotlib.pyplot as plt

#estimators
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn import linear_model

# model metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#cross validation
from sklearn.model_selection import train_test_split


In [4]:
# data import
missing_values=["n/a","na","--"]
rawData = pd.read_csv("/Users/csrxr/Desktop/Data_Analytics/Course05/default of credit card clients.csv", na_values=missing_values)

rawData.head(10)

rawData.columns =[x.lower() for x in rawData.columns]
rawData = rawData.rename(index=str,columns={"pay_0": "pay_1"})

rawData.columns



Index(['limit_bal', 'sex', 'education', 'marriage', 'age', 'pay_1', 'pay_2',
       'pay_3', 'pay_4', 'pay_5', 'pay_6', 'bill_amt1', 'bill_amt2',
       'bill_amt3', 'bill_amt4', 'bill_amt5', 'bill_amt6', 'pay_amt1',
       'pay_amt2', 'pay_amt3', 'pay_amt4', 'pay_amt5', 'pay_amt6',
       'default payment next month'],
      dtype='object')

In [5]:
features = rawData[[ 'sex', 'education', 'marriage', 'age', 'pay_1', 'pay_2',
       'pay_3', 'pay_4', 'pay_5', 'pay_6', 'bill_amt2',
       'bill_amt3', 'bill_amt4', 'bill_amt5', 'pay_amt1',
       'pay_amt2', 'pay_amt5', 'pay_amt6']]

In [6]:
#Features
features

sex  education  marriage  age  pay_1  pay_2  pay_3  pay_4  pay_5  \
0        2          2         1   24      2      2     -1     -1     -2   
1        2          2         2   26     -1      2      0      0      0   
2        2          2         2   34      0      0      0      0      0   
3        2          2         1   37      0      0      0      0      0   
4        1          2         1   57     -1      0     -1      0      0   
5        1          1         2   37      0      0      0      0      0   
6        1          1         2   29      0      0      0      0      0   
7        2          2         2   23      0     -1     -1      0      0   
8        2          3         1   28      0      0      2      0      0   
9        1          3         2   35     -2     -2     -2     -2     -1   
10       2          3         2   34      0      0      2      0      0   
11       2          1         2   51     -1     -1     -1     -1     -1   
12       2          2         2   41     -1      0     -1     -1     -1   
13       1          2         2   30      1      2      2      0      0   
14       1          1         2   29      0      0      0      0      0   
15       2          3         3   23      1      2      0      0      0   
16       1          1         2   24      0      0      2      2      2   
17       1          1         1   49      0      0      0     -1     -1   
18       2          1         1   49      1     -2     -2     -2     -2   
19       2          1         2   29      1     -2     -2     -2     -2   
20       2          3         2   39      0      0      0      0      0   
21       2          2         1   39     -1     -1     -1     -1     -1   
22       2          2         2   26      2      0      0      2      2   
23       2          1         1   40     -2     -2     -2     -2     -2   
24       1          1         2   23      0      0      0     -1      0   
25       1          3         2   23      0      0      0      0      0   
26       1          1         2   27      1     -2     -1     -1     -1   
27       2          3         2   30      0      0      0      0      0   
28       2          3         1   47     -1     -1     -1     -1     -1   
29       1          1         2   26      0      0      0      0      0   
...    ...        ...       ...  ...    ...    ...    ...    ...    ...   
29970    1          1         1   34     -1     -1     -1      0      0   
29971    1          3         1   36      0      0      0      0      0   
29972    1          1         1   37      0      0      0      0      0   
29973    1          2         1   35      1     -2     -2     -2     -2   
29974    1          2         1   37      1      2      2      2      0   
29975    1          2         1   41      0      0     -1     -1     -2   
29976    1          2         2   47      2      2      3      2      2   
29977    1          1         2   34      0      0      0      0      0   
29978    1          2         1   39      0      0      0      0      0   
29979    1          1         1   32     -2     -2     -2     -2     -2   
29980    1          3         2   42      0      0      0      0      0   
29981    1          2         1   44      1      2      2      2      0   
29982    1          2         1   36      0      0      0      0      0   
29983    1          2         1   44     -2     -2     -2     -2     -2   
29984    1          2         2   38     -1     -1     -2     -1     -1   
29985    1          1         2   30     -2     -2     -2     -2     -2   
29986    1          1         2   35     -1     -1     -2     -2     -2   
29987    1          1         2   34      0      0      0      0      0   
29988    1          1         1   34      0      0      0      0      0   
29989    1          1         2   35     -1     -1     -1     -1     -1   
29990    1          2         1   41      0      0      0      0      0   
29991    1          2         1 

In [7]:
#dependent variable
depVar = rawData['default payment next month']
depVar.head(10)

0    1
1    1
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: default payment next month, dtype: int64

In [8]:
#Trainiung Set
x_train = (features[:1000])
x_train.head()

sex  education  marriage  age  pay_1  pay_2  pay_3  pay_4  pay_5  pay_6  \
0    2          2         1   24      2      2     -1     -1     -2     -2   
1    2          2         2   26     -1      2      0      0      0      2   
2    2          2         2   34      0      0      0      0      0      0   
3    2          2         1   37      0      0      0      0      0      0   
4    1          2         1   57     -1      0     -1      0      0      0   

   bill_amt2  bill_amt3  bill_amt4  bill_amt5  pay_amt1  pay_amt2  pay_amt5  \
0       3102        689          0          0         0       689         0   
1       1725       2682       3272       3455         0      1000         0   
2      14027      13559      14331      14948      1518      1500      1000   
3      48233      49291      28314      28959      2000      2019      1069   
4       5670      35835      20940      19146      2000     36681       689   

   pay_amt6  
0         0  
1      2000  
2      5000  
3      1000  
4       679

In [9]:
#Dep Variable
y_train = depVar[:1000]
y_train_count = len(y_train.index)
print('The number of observations in the Y trainiung set are :',str(y_train_count))
y_train.head()

The number of observations in the Y trainiung set are : 1000


0    1
1    1
2    0
3    0
4    0
Name: default payment next month, dtype: int64

In [10]:
#Geround Truth (y_test)
y_test = depVar[-100:]
y_test_count = len(y_test.index)
print('The number of observations in the Y training set are :', str(y_test_count))
y_test.head()

The number of observations in the Y training set are : 100


29900    1
29901    0
29902    0
29903    0
29904    1
Name: default payment next month, dtype: int64

In [11]:
x = features    
y = depVar

# Cross Validation

In [12]:
#x_train, x_test, y_train, y_test = train_test_split(x_train, y_train)
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.25)

In [13]:
x_train.shape, x_test.shape

((22500, 18), (7500, 18))

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train)
x_train.shape, x_test.shape

((16875, 18), (5625, 18))

In [15]:
#Models
modelSVR = SVR()
modelRF = RandomForestRegressor()
modelLR = LinearRegression()

# Random Forest Regression Model Fitting and Scoring

In [16]:
modelRF.fit(x_train,y_train)
print(cross_val_score(modelRF,x_train,y_train))
modelRF.score(x_train,y_train)

/Users/csrxr/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/csrxr/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


[0.11970998 0.07659657 0.10008259]


0.8278857297789881

# Support Vector Regression Model Fitting and Scoring

In [17]:
modelSVR.fit(x_train,y_train)
print(cross_val_score(modelSVR, x_train, y_train)) 
modelSVR.score(x_train,y_train)

/Users/csrxr/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/csrxr/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/Users/csrxr/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/csrxr/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value 

[-0.01620128 -0.01591625 -0.01909427]


0.8956260882601627

# Linear Regression Model Fitting and Scoring

In [18]:
modelLR.fit(x_train,y_train)
print(cross_val_score(modelLR, x_train, y_train)) 
modelLR.score(x_train,y_train)

[0.13148259 0.11549284 0.11789359]


/Users/csrxr/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


0.12360024082035936

# RF Predictions 

In [34]:
predictions = modelRF.predict(x_test)
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from math import sqrt
rmse = sqrt (mean_squared_error(y_test,predictions))

predRsquared = r2_score(y_test,predictions)

#Make Predictions
predictions = modelRF.predict(x_test)
predRsquared = r2_score(y_test,predictions)
rmse = sqrt(mean_squared_error(y_test, predictions))
print('R Squared: %.3f' % predRsquared)
print('RMSE: %.3f' % rmse)

R Squared: 0.100
RMSE: 0.395


## RF Plotting

In [1]:
#plt.scatter(y_test, predictions, color=['blue','green'], alpha = 0.5)
#plt.xlabel('Ground Truth')
#plt.ylabel('Predictions')
#plt.show();